---
title: 'The unequal distribution of access to education and transport:
  insights from for São Paulo'
author: Ana I. Moreno-Monroy (Universitat Rovira i Virgili), Frederico R. Ramos (Fundação
  Getulio Vargas) and Robin Lovelace (University of Leeds)
output: 
  pdf_document: 
    keep_tex: yes
bibliography: school-access-bib.bib
---

```{r, echo=FALSE}
#date: '`r format(Sys.time(), ''%F'')`'
```


# Abstract

In many large Latin American cities such as São Paulo, growing social
and economic inequalities are embedded through unfair education and
transport systems. Good schools are mostly concentrated in wealthy
areas, while transport links to school are deficient in deprived areas,
exacerbating the issue. Inequalities in educational and transport
infrastructure are mutually reinforcing: the right to mobility is
intrinsically linked to the right to education. This is manifested by
the overlap between recent protests against unwanted changes to public
education and the social movements contesting increases in public
transport fares. Another manifestation is to be found in the concept of
school accessibility. This paper sheds light on the transport-education
inequality nexus with reference to a new school accessibility measure
applied São Paulo. By capturing both the unequal distribution of schools
and transport services across space, the index allows embedded
inequalities to be better understood and, with political will,
contested. Our index combines information on the spatial distribution of
children and adolescents by income categories, the location of existing
schools, the travel patterns of students, and the travel infrastructure
serving the school catchment area into a single measure. The index is
used to measure school accessibility locally across São Paulo, using
data sources from Population and School Censuses, commonly available in
Latin American cities. The results illustrate how existing inequalities
are amplified by variable accessibility to schools across income groups
and geographical space. We conclude that extending the concept of local
accessibility indicators to education can help to both contest and
constructively tackle embedded social inequalities.

# Introduction

**Contents:**

- Motivations
- General measures of accessibility
- School accessibility
- Literature review

References transport and social exclusion
[@hernandez2015mobilities] and [@hernandez2015mobilities] provides a general framework to undertand transport-related social exclusion in emerging economies

Evidence on access inequalities in the Brazilian context [@maia2016access]

Active travel children and adolescents in the SPMR [@de2015changes]
...

Travel to school is an everyday reality for millions of young people around the world.
The mode, duration, safety, comfort and pollution levels of this trip has huge
impacts on the future generation, yet has received relatively little academic
attention.


Travel options are vital for ensuring a more equitable supply of
educational opportunity to diverse groups. Conversely, poor accessibility
to deprived area can reinforce social inequalities, with long-term implications.
Based on this emerging context, this paper develops a school accessibility index
for local areas.

The first well-known attempt to define accessibility quantitatively was by @ingram1971concept, which presented a range of measures related to distance (Euclidean and network), barriers and different functions representing distance decay.

This early work made the distinction between accessibility indeces that apply to zones or single 'desire lines':
"relative accessibility is defined as a measure of the effort of overcoming spatial separation between two points, while the integral accessibility is defined as a measure of the effort of overcoming spatial separation between a point and all other points within an area"
[@allen1993accesibility].

# Area of study

The São Paulo Metropolitan Region (SPMR) is a large metropolis located in the South West of Brazil. It extends for over 7,700 squared kilometers and groups 39 different minucipalities. The estimated population in 2010 was close to 21 million. ... ADD MAP, etc.

#Data

For building our school accessibility index, we use data from three different sources. The first one is the 2008 School Census of the Brazilian National Institute of Educational Studies and Surveys (INEP), which provides information on the (universe) of public educational institutions, including their exact location (postal address) and the number of students enrolled in primary and secondary education. A clarification about the educational system in Brazil is in place here. Primary education *ensino fundamental* comprises nine years, divided on a first year of basic literacy *clase de alfabetização*, followed by eight "series". Primary education is mandatory for children aged 6-14. Secondary education lasts three years. In principle, the age range of secondary education students is 15-18. For each school, have geo-localized each postal adress for a total of XX public primary and XX secondary schools in the SPRM. 

Our second source is information the 2010 Population Census of Brazil at the *clase de alfabetização*, compiled and freely distributed by the Brazilian Institute of Statistics (IBGE). This spatial unit is equivalent to enumeration areas defined for surveying purposes, and contain on average 400 households. There is a total of 30,815 areas in the SPMR. IBGE also provides the digital networks containing the boundaries of the enumeration areas. From the census microdata, we have data on the number of inhabitants by age for each enumeration area. As the data was compiled in 2010 and we are interested in the number of children in primary school age (ages 6-14), and adolescents in secondary school age (ages 15-18), we calculate the count of children in the age range 8-16 (who were 6 and 14 in 2008) and adolescents in the age range 17-20 (aged 15-18 in 2008). The underlying assumption is that the location of children and adolescents did not change dramatically or systematically between 2008 and 2010, which is a reasonable assumption given thatr residential mobility is relatively low. using this procedure, we obtain a total number of children in primary school age of 2,731,999 (approximately 13 percent of the population) and a total of 1,730,252 tenneagers in secondary school age (approximately 8 percent of the population).       

Out last source is the 2007 Origin-Destination Household Travel Survey (O-D Survey), carried out by the São Paulo Metropolitan Transport Authority M\^{e}tro. we have information at the travel flow-level. geographic coordinates are provided for the origin and destination of each trip, as well as additional information such as trip purpose (includng education), trip duration, number of transfers and mode. The O-D Survey also provides the exact location of schools. The survey also provides relevant information on individuals undertaking the trips, such as their age, income range and educational status (including student). We focus on trips made by primary and secondary schools with an indicated motive ``education'' at the destination. The total number of trips (excluding missing values) was 11,845. Of these, 5.5 percent were multimodal. In those cases, we assing the mode of the trip leg with the largest duration. We add all trip leg durations (in minutes) to obtain the total trip duration. 

# Method: measuring school accessibility

We calculate three different accessibility measures for different modes: cumulative, gravitiy-based, and competitive.

The cumulative-opportunity measure for mode $M$ [@boisjoly2016] is defined as:

$$ CO_{i}^M= \sum_{j=1}^n(S_{j}f(C_{ij}) $$

$$ f(C_{ij}) = \left\{ 
                \begin{array}{ll}
                  1 if C_{ij}<=t\\
                  0 if C_{ij}<t
                \end{array}
              \right.
  $$ 

This measure counts the number of schools available from one area within a certain travel time by mode $M$ threshold. $C_{ij}$ is the travel cost (measured in time) between the centroid of zone i and the centroid of zone j. 

Gravity-based accessibility measure

In spite of its simplicity, Boisjoly and El-Geneidy (2016) have found that the cumulative-opportunity measure (using a 45 minute threshold) is highly correlated with a gravity-based accessibility measure ([@handy1997measuring], [@hansen1959accessibility]), defined as:

$$ A_{i}^M= \sum_{j=1}^n(S_{j}e^{\beta*C_{ij}}) $$

Where $A_{i}^M$ is the gravity accessibility at the centroid of area $i$ to all schools at area $j$ using mode $M$, and $\beta$ is a negative exponential cost function. The cost function, based on a negative exponential decay curve, includes reported number of school trips in the 2007 Origin-Destination Survey. (Here we can also use information from the school census on number of students per school to know how many students the area attracts). The proposed accessibility measure captures the fact that more proximate schools (S) are more attractive than those located further away. 

Competitive accessibility measure

The measures proposed above take into account the sptail distribution of schooling opportunities, but not the local demand for schooling. This is particularly relevant for our equity analysis, since it could be the case that higher areas are disproportionally served with respect to the number of potentail students living within a certain travel distance, whereas the opposite holds for lower-income areas.  In order to assess the mismatch between the demand and supply for schooling, we use the sum of students in schools in each area (the demand), and the sum of individuals within the school grade age-group living in each area (the supply) in the following competitive accessibility measure, first proposed by [@shen1998location] and adapted by El-Geneidy et al (2015):

$$ CA_{i}^M= \sum_{j=1}^n\frac{P_{j}-f(C_{ij})}{\sum_{k=1}^n(Y_{k}-f(C_{kj}))}$$

Where the numerator discounts the number of pupils in area $j$ $P_{j}$ by how far area $i$ is from area $j$ using the same function as before, and the denominator discounts the number of students (young adults) living in zone $k$ $Y_{k}$ by how far they are from area $j$. 
In this way, the discounted number of study places at each area is divided by the potential students available to fill those places, and then summed in order to obtain a single accessibility measure for each area $i$.  

In order to assess equality in access to schooling, we stratify our population of students in two student groups (we could do it for more income groups): the students living with a head of household who earns 1 minimum wage or less, and those living with a head of household who earns more than 1 minimum wage. The accessibility measures are based on student's travel times by different modes using data from the 2007 Origin-Destination survey. Alternatively, for the case of public transport, wet use actual transit times in 2015 for comparison (bilhete unico data?).

# Results

- Descriptive statistics about modal choice and travel time by AEPs and level of income
- Spatial Distribution of Schools and Transit-Dependent Students at the AEP Level 

# Discussion

# Conclusion

# References

<!--
  
  --> 

